# Generated by Django 3.2.16 on 2022-11-26 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appName', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('next_question_when_yes', models.IntegerField(blank=True, null=True)),
                ('next_question_when_no', models.IntegerField(blank=True, null=True)),
                ('solution_when_yes', models.IntegerField(blank=True, null=True)),
                ('solution_when_no', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.CharField(max_length=400)),
                ('error_number', models.IntegerField()),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appName.errornumber')),
            ],
        ),
        migrations.CreateModel(
            name='WorkDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order', models.IntegerField()),
                ('answer', models.CharField(max_length=400)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appName.question')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appName.work')),
            ],
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.AddField(
            model_name='errornumber',
            name='next_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appName.question'),
        ),
    ]
