# Generated by Django 3.2.16 on 2022-11-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appName', '0002_auto_20221126_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='error_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
