# Generated by Django 3.2.16 on 2022-11-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appName', '0003_question_error_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='error_number',
            field=models.IntegerField(default=1),
        ),
    ]
